version: "3.8"

services:
  postgresdb:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=notes
    ports:
      - 5432:5432
